[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D", # pydocstyle (D)
  "T201", # print
  "ERA001", # commented-out-code
  # "ANN", # flake8-annotations (ANN)
  # "ANN001", # missing-type-function-argument
  "ANN002", # missing-type-args
  "ANN003", # missing-type-kwargs
  "ANN101", # missing-type-self
  # "ANN201", # missing-return-type-undocumented-public-function
  "PLR0913", # too-many-arguments
  "G004", # logging-f-string
  "COM812", # missing-trailing-comma
  "INP001", # implicit-namespace-package
]

[tool.ruff.lint.per-file-ignores]
"**/{tests,docs,tools}/**/*" = []

[tool.ruff.format]
# skip-magic-trailing-comma = true
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"
